import { createHash, randomBytes } from 'node:crypto';
import type { FastifyInstance } from 'fastify'; import type { SettingsStore } from '../config.js';
const sessions=new Map<string,{verifier:string;at:number}>(); const b64=(b:Buffer)=>b.toString('base64url');
const SESSION_TTL_MS=10*60_000;
/** Abandoned logins (closed popup, error redirect) never hit the callback — sweep them so the map can't grow unbounded. */
const sweepSessions=()=>{const cutoff=Date.now()-SESSION_TTL_MS;for(const [k,v] of sessions)if(v.at<cutoff)sessions.delete(k);};
export function registerSpotifyAuth(app:FastifyInstance, store:SettingsStore) {
  app.get('/auth/spotify/login', async (_req, reply)=>{const s=store.get(); if(!s.spotify.clientId) return reply.code(400).send('Configure Spotify client ID first.'); sweepSessions(); const verifier=b64(randomBytes(48)); const state=b64(randomBytes(24)); sessions.set(state,{verifier,at:Date.now()}); const challenge=b64(createHash('sha256').update(verifier).digest()); const u=new URL('https://accounts.spotify.com/authorize'); u.search=new URLSearchParams({response_type:'code',client_id:s.spotify.clientId,redirect_uri:s.spotify.redirectUri,code_challenge_method:'S256',code_challenge:challenge,state,scope:'playlist-modify-private playlist-read-private user-read-private'}).toString(); return reply.redirect(u.toString());});
  app.get('/auth/spotify/callback', async (req,reply)=>{const q=req.query as {code?:string;state?:string;error?:string}; const s=store.get(); const session=q.state? sessions.get(q.state):undefined; if(q.error||!q.code||!session||!s.spotify.clientId) return reply.code(400).type('text/html').send('<p>Spotify authorization failed. You can close this tab.</p>'); sessions.delete(q.state!); const body=new URLSearchParams({grant_type:'authorization_code',code:q.code,redirect_uri:s.spotify.redirectUri,client_id:s.spotify.clientId,code_verifier:session.verifier}); const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body,signal:AbortSignal.timeout(10_000)}); if(!r.ok) return reply.code(502).send('Spotify token exchange failed'); const j=await r.json() as {access_token:string;refresh_token:string;expires_in:number}; store.update({spotify:{...s.spotify,tokens:{accessToken:j.access_token,refreshToken:j.refresh_token,expiresAt:Date.now()+j.expires_in*1000}}}); return reply.type('text/html').send('<p>Spotify connected. You can close this tab.</p>');});
}
