import { createHash } from 'node:crypto'; import type { TrackCandidate, SpotifyResolution } from '@setflow/shared';
import { cacheDb } from '../cache/db.js'; import { SpotifyClient } from './client.js';
const norm=(s:string)=>s.toLowerCase().replace(/\([^)]*\)|\[[^\]]*\]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const mixNorm=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const tokens=(s:string)=>new Set(norm(s).split(' ').filter(Boolean)); const overlap=(a:string,b:string)=>{const A=tokens(a),B=tokens(b); return [...A].filter(x=>B.has(x)).length/Math.max(1,Math.max(A.size,B.size));};
export interface SpotifySearchItem { id:string; uri:string; external_urls?:{spotify?:string}; name:string; artists:{name:string}[]; album?:{images?:{url:string}[]}; duration_ms:number; }
export function scoreSearchResult(c:Pick<TrackCandidate,'artist'|'title'|'mix'>, x:SpotifySearchItem):{score:number;quality:SpotifyResolution['matchQuality']} { const artist=x.artists.map(a=>a.name).join(' '), title=x.name; if(c.mix && mixNorm(title).includes(mixNorm(c.mix))) return {score:1,quality:'exact-mix'}; if(norm(c.title)===norm(title)&&overlap(c.artist,artist)>=.6) return {score:.9,quality:'title-match'}; const score=.55*overlap(c.title,title)+.45*overlap(c.artist,artist); return {score,quality:'fuzzy'}; }
let audioFeaturesAvailable:boolean|undefined;
export async function probeAudioFeatures(client:SpotifyClient):Promise<boolean>{if(audioFeaturesAvailable!==undefined)return audioFeaturesAvailable; try{const r=await client.fetch('/audio-features/0000000000000000000000'); audioFeaturesAvailable=r.status!==403&&r.status!==404; }catch{audioFeaturesAvailable=false;} return audioFeaturesAvailable;}
export async function resolveTrack(candidate:TrackCandidate, client:SpotifyClient):Promise<SpotifyResolution|null>{ if(process.env.SETFLOW_MOCK==='1'){const id=createHash('sha1').update(`${candidate.artist}|${candidate.title}|${candidate.mix}`).digest('hex').slice(0,22); return {trackId:`mock${id}`,uri:`spotify:track:mock${id}`,url:`https://open.spotify.com/track/mock${id}`,resolvedArtist:candidate.artist,resolvedTitle:`${candidate.title}${candidate.mix?` (${candidate.mix})`:''}`,albumArtUrl:null,durationMs:360000,matchQuality:candidate.mix?'exact-mix':'title-match'};}
  // Cascade: mix-qualified first (catches the exact remix), then mixless field query, then plain
  // free text. Brains label almost everything "Original/Extended Mix" — when the real Spotify title
  // has no such suffix, the mix-qualified query returns zero items and must not end the search.
  const base=`track:${candidate.title} artist:${candidate.artist}`; const queries=candidate.mix?[`${base} ${candidate.mix}`,base]:[base]; queries.push(`${candidate.title} ${candidate.artist}`);
  let items:SpotifySearchItem[]=[];
  for(const query of queries){const key=createHash('sha256').update(query).digest('hex'); let batch=cacheDb.search(key) as SpotifySearchItem[]|null; if(!batch){const r=await client.fetch(`/search?${new URLSearchParams({q:query,type:'track',limit:'10'})}`); if(!r.ok)return null; batch=((await r.json()) as {tracks?:{items?:SpotifySearchItem[]}}).tracks?.items??[]; cacheDb.setSearch(key,batch);} if(batch.length){items=batch;break;}}
  const ranked=items.map(x=>({x,...scoreSearchResult(candidate,x)})).sort((a,b)=>b.score-a.score)[0]; if(!ranked||ranked.score<.6)return null; const x=ranked.x; const result={trackId:x.id,uri:x.uri,url:x.external_urls?.spotify??`https://open.spotify.com/track/${x.id}`,resolvedArtist:x.artists[0]?.name??candidate.artist,resolvedTitle:x.name,albumArtUrl:x.album?.images?.[0]?.url??null,durationMs:x.duration_ms,matchQuality:ranked.quality}; cacheDb.setTrack(x.id,result); return result; }
