import { describe, expect, it } from 'vitest'; import { z } from 'zod';
import { mkdtempSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path';
import { ConstraintsSchema, IntentSchema } from '@setflow/shared';
import { extractJsonObject, parseWithRepair } from './brain/jsonExtract.js'; import { DEFAULT_PROMPTS, buildPrompt } from './brain/prompts.js'; import { MockBrainAdapter } from './brain/adapters/mock.js'; import { buildSetDocument } from './pipeline/assemble.js'; import { scoreSearchResult } from './spotify/resolve.js'; import { csv } from './export/csv.js'; import { m3u8 } from './export/m3u8.js'; import { rekordbox } from './export/rekordbox.js'; import { textTracklist } from './export/text.js'; import { buildYouTubeUrl } from './pipeline/youtube.js'; import { SettingsStore, defaultSettings, redactSettings } from './config.js';
describe('JSON extraction',()=>{it('handles fences and prose, rejecting truncation',()=>{expect(extractJsonObject('hello ```json\n{"ok":true}\n``` bye')).toEqual({ok:true});expect(()=>extractJsonObject('before {"ok":')).toThrow('Truncated');expect(parseWithRepair('{"x":2}',z.object({x:z.number()}))).toEqual({x:2});});});
describe('prompts',()=>{it('includes constraints and JSON-only direction',()=>{const s=defaultSettings(),c=ConstraintsSchema.parse({harmonicStrictness:.9});const p=buildPrompt({kind:'propose',context:{intent:IntentSchema.parse({mode:'vibe',vibeText:'sunset'}),constraints:c,targetCurve:null}},s);expect(p).toContain('ONLY a valid JSON object');expect(p).toContain('harmonicStrictness');expect(DEFAULT_PROMPTS.propose).toContain('20-30');});});
describe('mock pipeline and exports',()=>{it('builds a pool/options/transitions and well-formed exports',async()=>{const brain=new MockBrainAdapter();const p=await brain.request({kind:'propose',context:{intent:IntentSchema.parse({mode:'vibe',vibeText:'golden hour'}),constraints:ConstraintsSchema.parse({}),targetCurve:null}}) as any;const d=buildSetDocument(IntentSchema.parse({mode:'vibe',vibeText:'golden hour'}),ConstraintsSchema.parse({}),p,'claude-cli');expect(d.pool.length).toBeGreaterThanOrEqual(20);expect(d.options.map(x=>x.id)).toEqual(['A','B']);expect(d.options[0]!.transitions.length).toBe(d.options[0]!.trackIds.length-1);expect(d.options[0]!.transitions[0]!.camelotPath).toMatch(/^.+→.+$/);expect(Array.isArray(d.options[0]!.transitions[0]!.warnings)).toBe(true);expect(csv(d,'A').trim().split('\n').length).toBe(d.options[0]!.trackIds.length+1);expect(m3u8(d,'A')).toContain('#EXTM3U');expect(rekordbox(d,'A')).toMatch(/<DJ_PLAYLISTS[\s>]/);expect(textTracklist(d,'A')).toContain('Lane 8');});});
describe('resolution scoring',()=>{it('prefers exact named mix over title match',()=>{const c:any={artist:'Artist',title:'Song',mix:'Club Mix'};const base={id:'1',uri:'spotify:track:1',artists:[{name:'Artist'}],duration_ms:1};expect(scoreSearchResult(c,{...base,name:'Song (Club Mix)'}).quality).toBe('exact-mix');expect(scoreSearchResult(c,{...base,name:'Song'}).quality).toBe('title-match');});});
describe('settings and youtube',()=>{it('roundtrips settings, redacts secrets, and creates fallback URL',async()=>{const store=new SettingsStore(join(mkdtempSync(join(tmpdir(),'setflow-')),'settings.json'));store.update({brain:{...store.get().brain,anthropicApiKey:'secret'},sources:{...store.get().sources,youtubeApiKey:undefined}});expect(redactSettings(store.get())).toMatchObject({brain:{hasAnthropicApiKey:true,anthropicApiKey:undefined}});const url=await buildYouTubeUrl('Lane 8','Atlas','Extended Mix',store.get());expect(url).toContain('youtube.com/results?search_query=');});});
