import { AnimatePresence, motion } from 'framer-motion';
import { useCallback, useRef, useState } from 'react';
import { api } from '../api';
import { useSetflow } from '../store';
import { useTheme } from '../theme/ThemeProvider';
import { useOutsideClose } from './helpers';

export function SetHistory() {
  const history = useSetflow((s) => s.history); const loadSet = useSetflow((s) => s.loadSet); const remix = useSetflow((s) => s.remix); const refreshHistory = useSetflow((s) => s.refreshHistory); const { motion: springs } = useTheme();
  const [open, setOpen] = useState(false); const [remixing, setRemixing] = useState<string | null>(null); const [flavor, setFlavor] = useState(''); const ref = useRef<HTMLDivElement>(null); const close = useCallback(() => setOpen(false), []); useOutsideClose(ref, open, close);
  const remove = async (id: string) => { await api.deleteSet(id); await refreshHistory(); };
  return <div ref={ref} style={{ position: 'relative' }}><button className="btn quiet" onClick={() => setOpen((value) => !value)}>history</button><AnimatePresence>{open && <motion.div className="panel" initial={{ opacity: 0, scale: .98, y: -4 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: .98, y: -4 }} transition={springs.microSpring} style={{ position: 'absolute', right: 0, top: 'calc(100% + 8px)', width: 320, zIndex: 20, padding: 8 }}><div className="label" style={{ padding: 8 }}>history</div>{history.length === 0 ? <p style={{ color: 'var(--c-text-muted)', padding: 8, margin: 0 }}>no sets yet, architect your first.</p> : history.map((set) => <div key={set.id} style={{ padding: 8, borderTop: 'var(--tx-border-w) solid var(--c-panel-border)' }}><button onClick={() => { void loadSet(set.id); close(); }} style={{ width: '100%', textAlign: 'left' }}><b>{set.name}</b><br /><span className="label">{new Date(set.createdAt).toLocaleDateString()} · {set.mode} · {set.trackCount} tracks</span></button><div style={{ display: 'flex', gap: 5, marginTop: 4 }}><button className="btn quiet" style={{ padding: '2px 4px', fontSize: 11 }} onClick={() => setRemixing(set.id)}>remix</button><button className="btn quiet danger-text" style={{ padding: '2px 4px', fontSize: 11 }} onClick={() => void remove(set.id)}>delete</button></div>{remixing === set.id && <div style={{ display: 'flex', gap: 4, marginTop: 5 }}><input style={{ minWidth: 0, flex: 1 }} value={flavor} onChange={(event) => setFlavor(event.target.value)} placeholder="darker, more hypnotic" /><button className="btn quiet" onClick={() => { if (flavor.trim()) void remix(set.id, flavor.trim()); setRemixing(null); setFlavor(''); close(); }}>go</button></div>}</div>)}</motion.div>}</AnimatePresence></div>;
}
