import { useEffect } from 'react';
import type { SetDocument, TrackCandidate } from '@setflow/shared';
import { formatDuration, formatDelta, trackName } from './helpers';

export function SetSheet({ doc, optionId, onClose }: { doc: SetDocument; optionId: string; onClose: () => void }) {
  const option = doc.options.find((item) => item.id === optionId); const tracks = (option?.trackIds ?? []).map((id) => doc.pool.find((track) => track.id === id)).filter((track): track is TrackCandidate => Boolean(track));
  useEffect(() => { document.body.classList.add('printing-sheet'); return () => document.body.classList.remove('printing-sheet'); }, []);
  const values = option?.predictedEnergies ?? []; const points = values.map((value, index) => `${index * (100 / Math.max(1, values.length - 1))},${56 - value * 5}`).join(' ');
  return <div style={{ position: 'fixed', inset: 0, zIndex: 100, overflow: 'auto', background: 'white', color: 'black', padding: 32, fontFamily: 'system-ui, sans-serif' }}><style>{'@media print { body.printing-sheet .app, body.printing-sheet > #root { display: none !important; } body.printing-sheet [data-setflow-sheet] { display: block !important; position: static !important; padding: 0 !important; } }'}</style><main data-setflow-sheet="true" style={{ maxWidth: 760, margin: '0 auto' }}><div className="no-print" style={{ display: 'flex', justifyContent: 'flex-end', gap: 8, marginBottom: 20 }}><button className="btn" onClick={() => window.print()}>Print</button><button className="btn" onClick={onClose}>Close</button></div><header style={{ borderBottom: '1px solid black', paddingBottom: 12 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 16 }}><h1 style={{ fontSize: 28 }}>{doc.name}</h1><span>{new Date(doc.createdAt).toLocaleDateString()}</span></div><p style={{ margin: '4px 0' }}>{option?.label ?? optionId} · {doc.intent.vibeText || doc.intent.seedTrack || doc.intent.artists?.join(', ') || 'crafted DJ journey'}</p><svg viewBox="0 0 100 60" width="100%" height="70" aria-label="Energy arc"><polyline points={points} fill="none" stroke="black" strokeWidth="1.5" /></svg></header><div style={{ fontFamily: 'ui-monospace, monospace', fontSize: 11 }}><div style={{ display: 'grid', gridTemplateColumns: '28px 1fr 42px 44px 46px 44px', gap: 8, padding: '10px 0 4px', borderBottom: '1px solid black' }}><b>#</b><b>track</b><b>key</b><b>bpm</b><b>energy</b><b>time</b></div>{tracks.map((track, index) => <div key={track.id}><div style={{ display: 'grid', gridTemplateColumns: '28px 1fr 42px 44px 46px 44px', gap: 8, padding: '5px 0' }}><span>{index + 1}</span><span>{trackName(track)}</span><span>{track.key.value}</span><span>{Math.round(track.bpm.value)}</span><span>{track.energy.value}</span><span>{formatDuration(track.durationMs?.value)}</span></div>{option?.transitions[index] && <div style={{ padding: '0 0 6px 28px', fontSize: 10 }}>{option.transitions[index]!.camelotPath} · {formatDelta(option.transitions[index]!.bpmDeltaPercent)} · {option.transitions[index]!.blend.replace('-', ' ')} · {option.transitions[index]!.note}</div>}</div>)}</div><footer style={{ borderTop: '1px solid black', marginTop: 16, paddingTop: 8, fontSize: 10 }}>SETFLOW set sheet · data from Spotify / Deezer / GetSongBPM</footer></main></div>;
}
