import { z } from 'zod';
import { BrainAlternativesSchema, BrainProposalSchema, BrainReplacementSchema, type BrainAdapter, type BrainRequest } from '@setflow/shared';
import type { Settings } from '../config.js'; import { buildPrompt } from './prompts.js'; import { parseWithRepair } from './jsonExtract.js';
import { ClaudeCliAdapter } from './adapters/claudeCli.js'; import { CodexCliAdapter } from './adapters/codexCli.js'; import { AnthropicApiAdapter } from './adapters/anthropicApi.js'; import { MockBrainAdapter } from './adapters/mock.js';
export class BrainError extends Error { constructor(message:string, public readonly causeText?:string){super(message);this.name='BrainError';} }
export function getAdapter(settings:Settings, opts?:{forceReal?:boolean}):BrainAdapter { if(!opts?.forceReal && process.env.SETFLOW_MOCK==='1') return new MockBrainAdapter(); if(settings.brain.adapterId==='codex-cli') return new CodexCliAdapter(settings.brain.codexCliPath); if(settings.brain.adapterId==='anthropic-api') return new AnthropicApiAdapter(settings.brain.anthropicApiKey,settings.brain.anthropicModel); return new ClaudeCliAdapter(settings.brain.claudeCliPath); }
/** LLMs drift from the documented replace shape (flattened track fields, "resolved"/"tracks" keys,
 * "index"/"reason" instead of "replacesIndex"/"why"). Normalize the common drifts before zod;
 * missing estimates get neutral priors — the pipeline verifies them against real data anyway. */
function normalizeReplacements(j:unknown):unknown { if(!j||typeof j!=='object') return j; const o=j as Record<string,unknown>; let arr=Array.isArray(o.replacements)?o.replacements:Array.isArray(o.resolved)?o.resolved:Array.isArray(o.tracks)?o.tracks:Array.isArray(j)?j as unknown[]:null; if(!arr) return j; return {replacements:arr.map(r=>{ if(!r||typeof r!=='object') return r; const x=r as Record<string,unknown>; if(x.track&&typeof x.track==='object'){const t=x.track as Record<string,unknown>; return {replacesIndex:x.replacesIndex??x.index??0,track:{estBpm:120,estEnergy:5,...t,why:t.why??t.reason??''}};} const {replacesIndex,index,reason,...rest}=x; return {replacesIndex:replacesIndex??index??0,track:{estBpm:120,estEnergy:5,...rest,why:rest.why??reason??''}}; })}; }
function schemaFor(request:BrainRequest): z.ZodTypeAny { return request.kind==='replace'?z.preprocess(normalizeReplacements,BrainReplacementSchema):request.kind==='alternatives'?BrainAlternativesSchema:BrainProposalSchema; }
export async function callBrain(request:BrainRequest, settings:Settings):Promise<any> { const adapter=getAdapter(settings); if(adapter instanceof MockBrainAdapter) return adapter.request(request); const schema=schemaFor(request); const prompt=buildPrompt(request,settings); let raw=''; try { raw=await adapter.complete(prompt,{timeoutMs:settings.brain.timeoutMs}); return parseWithRepair(raw,schema); } catch(error) { try { const repair=`Your previous output failed validation: ${error instanceof Error?error.message:String(error)}. Return ONLY corrected valid JSON matching the schema. Original request: ${prompt}`; return parseWithRepair(await adapter.complete(repair,{timeoutMs:settings.brain.timeoutMs}),schema); } catch(repairError) { throw new BrainError('Brain output could not be validated', repairError instanceof Error?repairError.message:raw); } } }
